(function(){"use strict";$(()=>{const d=$("#guidedFlowPopup"),h=$("#riid").text(),w=e=>{document.cookie="expValue="+e+"; max-age="+28*24*60*60};$("#guidedFlowPopup").on("hidden.bs.modal",function(){w("none")});let s=null,l=null;function m(){const e=$("#guidedFlowPopup");var n=document.cookie.replace(/(?:(?:^|.*;\s*)expValue\s*\=\s*([^;]*).*$)|^.*$/,"$1");n&&n.length>0?$("#guidedFlowPopup").attr("data-show","false"):$("#guidedFlowPopup").attr("data-show","true"),e.length&&e.data("show")&&e.data("show")==!0&&setTimeout(()=>{e.modal("show")},e.data("modaltimer"))}let c=0,u=setInterval(function(){c++,(window.OneTrust||c===10)&&(c===10?clearInterval(u):(clearInterval(u),!r()&&window.OneTrust&&window.OneTrust.OnConsentChanged(()=>{r()})))},1e3);const r=()=>{const e="002";return window.OneTrust.IsAlertBoxClosed()&&OptanonActiveGroups&&OptanonActiveGroups.indexOf(e)>-1?(x("expValue")||m(),!0):!1},x=e=>{const n=e+"=",o=decodeURIComponent(document.cookie).split("; ");let a;return o.forEach(i=>{i.indexOf(n)===0&&(a=i.substring(n.length))}),a},p=e=>{$(".fadeout-content").fadeOut("slow",function(){$("#eyebrowTitle").text(e.EyebrowTitle),$("#title").text(e.Title),$("#defaultImage").attr("src",e.DefaultImage),$("#finalwaitmessage").text(e.FinalWaitingMessage),$("#finalEyebrowTitle").text(e.FinalScreenEyebrowTitle),$("#animatedLogo").attr("src",e.FinalScreenAnimatedLogo);const n=e.ButtonList.map((t,o)=>{const a=t.ExperienceValue!=null?t.ExperienceValue:0,i=t.ButtonLink!=null&&t.ButtonLink!==""?t.ButtonLink:"#";return`
                <div class="col-12 p-2">
                    <a href="${i}" class="guided-pop-up-btn expBtn ${i!=="#"?"has-link":""} position-relative" 
                    data-exp-value="${a}" 
                    data-riid="${h}"
                    data-tag-item="${t.DataTagItemField}"
                    data-image="${t.Image||""}"
                    data-modal-index="${o}" title="${t.ButtonText}">
                    ${t.ButtonText}<i class="fal fa-long-arrow-right"></i></a>
                </div>
            `}).join("");$("#buttonList").html(n),$(".fadeout-content").fadeIn("slow")})},k=(e,n,t,o)=>{if(e)p(e),s=e,d.modal("show");else if(document.cookie="expValue="+n+"; max-age="+28*24*60*60,o&&o.length>0?dataLayer.push({event:"gfp",gfp_experience_value:n,ri_id:o}):dataLayer.push({event:"gfp",gfp_experience_value:n}),t&&t.trim()!==""){const a=$(".col-md-6.col-sm-12.text-center.bg-light.pt-5"),i=$("#animatedLogo").attr("src"),g=$("#finalEyebrowTitle").text(),v=$("#finalwaitmessage").text();a.html(`
                    <h6>${g}</h6>
                    <h3>${v}</h3>
                    <div><img src="${i}" class="animated-gif" /></div>
                `),setTimeout(()=>{window.location.href=t},2e3)}else window.location.href=t},f=d.data("guided-flow-model");p(f),s=f,$("#buttonList").on("mouseenter",".expBtn.has-link",function(){const e='<span class="svg-link"><svg class="link-icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7 17L17 7M17 7H7M17 7V17" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></span>';$(this).append(e)}),$("#buttonList").on("mouseleave",".expBtn.has-link",function(){$(this).find(".link-icon").remove()}),$("#buttonList").on("click",".expBtn",function(e){e.preventDefault();const n=$(this).data("modal-index"),t=$(this).data("exp-value"),o=$(this).attr("href"),a=$(this).data("riid"),i=s.ButtonList[n].NextStepModal;k(i,t,o,a)}),$("#buttonList").on("mouseenter",".expBtn",function(){const e=$(this).data("image");e&&($("#defaultImage").attr("src",e),l=e)}),$("#buttonList").on("mouseleave",".expBtn",function(){l&&$("#defaultImage").attr("src",l)})})})();
